services:
  web:
    build: .
    image: danielhenrique090109/baby_corpback:latest
    command: sh -c "python manage.py migrate --noinput && gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:////app/data/db.sqlite3
      MODE: DEVELOPMENT
      DEBUG: "True"
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
