# Generated by Django 5.2.12 on 2026-05-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilbaba',
            name='dtnasc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilbaba',
            name='formacao',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='perfilbaba',
            name='habilidades',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='perfilbaba',
            name='sobre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilbaba',
            name='valor_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
