# Generated by Django 5.2.12 on 2026-05-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilbaba_dtnasc_perfilbaba_formacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='qtd_criancas',
            field=models.IntegerField(verbose_name='Quantidade de Crianças'),
        ),
        migrations.AlterField(
            model_name='perfilbaba',
            name='dtnasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
