# Generated by Django 6.0.5 on 2026-05-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilbaba_dtnasc_perfilbaba_formacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='qtd_criancas',
            field=models.IntegerField(verbose_name='Quantidade de Crianças'),
        ),
        migrations.AlterField(
            model_name='perfilbaba',
            name='dtnasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
