# Generated by Django 5.2.12 on 2026-05-29 14:47

import core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_agendamento_qtd_criancas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpai',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=11, unique=True, validators=[core.models.user.validar_cpf]),
        ),
    ]
