# Generated by Django 5.2.14 on 2026-06-03 23:46

import django_cpf_cnpj.fields
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilbaba',
            name='sobre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BR'),
        ),
    ]
