# Generated by Django 5.2.14 on 2026-06-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_perfilbaba_sobre_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilpai',
            name='endereco',
        ),
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
