# Generated by Django 5.2.12 on 2026-04-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_passage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pai',
            fields=[
                ('idpai', models.AutoField(primary_key=True, serialize=False)),
                ('QuantidadeFilhos', models.IntegerField()),
            ],
        ),
    ]
