# Generated by Django 5.2.12 on 2026-04-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baba',
            fields=[
                ('idbaba', models.AutoField(primary_key=True, serialize=False)),
                ('habilidades', models.CharField(max_length=700)),
                ('dtnasc', models.DateField()),
                ('idade', models.IntegerField()),
                ('Formacao', models.CharField(max_length=700)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sobre', models.CharField(max_length=700)),
            ],
        ),
    ]
