# Generated by Django 5.2.14 on 2026-06-12 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_perfilpai_endereco_usuario_bairro_usuario_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('idade', models.PositiveIntegerField()),
                ('alergias', models.TextField(blank=True, null=True)),
                ('condicoes', models.TextField(blank=True, null=True, verbose_name='Condições físicas/mentais')),
                ('perfil_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criancas', to='core.perfilpai')),
            ],
        ),
    ]
