# Generated by Django 5.2.12 on 2026-04-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_baba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('precoagendamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtdcriancas', models.IntegerField()),
            ],
        ),
    ]
