# Generated by Django 5.2.12 on 2026-04-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='celular',
            field=models.CharField(default='47999999999', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='89789789789', max_length=14),
        ),
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.CharField(default='Endereço Exemplo', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Digite o email coreto', max_length=255, unique=True, verbose_name='Digite seu email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(db_column='iduser', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Nome Exemplo', help_text='Nome por favor', max_length=60, verbose_name='Digite seu nome'),
        ),
    ]
