# Generated by Django 5.2.14 on 2026-07-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='qtd_criancas',
            field=models.IntegerField(),
        ),
    ]
