# Generated by Django 5.2.14 on 2026-07-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='primeiro_nome',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_nome',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
