# Generated by Django 5.2.12 on 2026-04-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_celular_alter_user_cpf_alter_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='endereco',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(db_column='iduser', primary_key=True, serialize=False),
        ),
    ]
