# Generated by Django 5.2.14 on 2026-07-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usuario_primeiro_nome_usuario_ultimo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilbaba',
            name='experiencia_anos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpai',
            name='numero_filhos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
