# Generated by Django 5.2.12 on 2026-04-22 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_user_login_alter_user_celular_alter_user_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baba',
            name='user',
            field=models.ForeignKey(db_column='iduser', default=4632467, on_delete=django.db.models.deletion.PROTECT, related_name='babas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
