# Generated by Django 5.2.14 on 2026-08-10 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_perfilbaba_experiencia_anos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilBabaCompleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perfil_baba', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completude', to='core.perfilbaba')),
            ],
        ),
    ]
