# Generated by Django 5.2.14 on 2026-08-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_perfilbabacompleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
