# Generated by Django 5.2.14 on 2026-08-12 20:31
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_perfilbabacompleta'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='usuario',
                    name='username',
                ),
            ],
            database_operations=[],
        ),
    ]
