# Generated by Django 5.2.12 on 2026-04-23 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_baba_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='Idbaba',
            field=models.ForeignKey(db_column='idbaba', default=12345, on_delete=django.db.models.deletion.PROTECT, related_name='agendamento', to='core.baba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pai',
            name='user',
            field=models.ForeignKey(db_column='iduser', default=12345, on_delete=django.db.models.deletion.PROTECT, related_name='pais', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
