# Generated by Django 5.2.12 on 2026-04-23 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_agendamento_idbaba_pai_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='idpai',
            field=models.ForeignKey(db_column='idpai', default=12345, on_delete=django.db.models.deletion.PROTECT, related_name='agendamento', to='core.pai'),
            preserve_default=False,
        ),
    ]
