# Generated by Django 5.2.14 on 2026-08-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_usuario_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
